export const destinations = [
  {
    id: "uae",
    name: "UAE Groups",
    description: "Explore Dubai with exclusive group discounts",
    image: "/images/dest-uae.jpg",
    slug: "uae-groups",
  },
  {
    id: "ksa",
    name: "KSA Groups",
    description: "Travel to Saudi Arabia with exclusive rates",
    image: "/images/dest-ksa.jpg",
    slug: "ksa-groups",
  },
  {
    id: "umrah",
    name: "Umrah Groups",
    description: "Special packages for your spiritual journey",
    image: "/images/dest-umrah.jpg",
    slug: "umrah-groups",
  },
  {
    id: "muscat",
    name: "Muscat Groups",
    description: "Discover the beauty of Oman",
    image: "/images/dest-muscat.jpg",
    slug: "muscat-groups",
  },
  {
    id: "qatar",
    name: "Qatar Groups",
    description: "Experience Qatar's modern marvels",
    image: "/images/dest-qatar.jpg",
    slug: "qatar-groups",
  },
  {
    id: "bahrain",
    name: "Bahrain Groups",
    description: "Discover Bahrain's rich culture",
    image: "/images/dest-bahrain.jpg",
    slug: "bahrain-groups",
  },
  {
    id: "uk",
    name: "UK Groups",
    description: "Explore the United Kingdom",
    image: "/images/dest-uk.jpg",
    slug: "uk-groups",
  },
  {
    id: "all",
    name: "All Groups",
    description: "Browse all available destinations",
    image: "/images/dest-all.jpg",
    slug: "all-groups",
  },
];

export const airlines = [
  { id: "fly-jinnah", name: "FLY JINNAH", logo: "FJ" },
  { id: "air-sial", name: "AIR SIAL", logo: "AS" },
  { id: "air-arabia", name: "AIR ARABIA", logo: "AA" },
  { id: "pia", name: "PIA", logo: "PK" },
];

export const sectors = [
  { id: "isb-shj", from: "ISB", to: "SHJ", name: "Islamabad - Sharjah" },
  { id: "isb-dxb", from: "ISB", to: "DXB", name: "Islamabad - Dubai" },
  { id: "isb-auh", from: "ISB", to: "AUH", name: "Islamabad - Abu Dhabi" },
  { id: "lhe-dxb", from: "LHE", to: "DXB", name: "Lahore - Dubai" },
  { id: "khi-dxb", from: "KHI", to: "DXB", name: "Karachi - Dubai" },
];

export const flightsData = {
  uae: [
    {
      id: "AG2006",
      date: "26-01-2026",
      sector: "ISB-SHJ",
      flight: "9P742",
      airline: "fly-jinnah",
      airlineName: "Fly Jinnah",
      departureTime: "20:15",
      arrivalTime: "22:50",
      baggage: "20+7 KG",
      meal: false,
      seatsAvailable: 12,
      price: 90000,
      currency: "PKR",
    },
    {
      id: "AG2019",
      date: "27-01-2026",
      sector: "ISB-SHJ",
      flight: "9P742",
      airline: "fly-jinnah",
      airlineName: "Fly Jinnah",
      departureTime: "20:18",
      arrivalTime: "22:50",
      baggage: "20+7 KG",
      meal: false,
      seatsAvailable: 8,
      price: 87000,
      currency: "PKR",
    },
    {
      id: "AG2007",
      date: "28-01-2026",
      sector: "ISB-SHJ",
      flight: "9P740",
      airline: "fly-jinnah",
      airlineName: "Fly Jinnah",
      departureTime: "06:00",
      arrivalTime: "08:35",
      baggage: "20+7 KG",
      meal: false,
      seatsAvailable: 15,
      price: 83000,
      currency: "PKR",
    },
    {
      id: "AG2020",
      date: "30-01-2026",
      sector: "ISB-SHJ",
      flight: "9P740",
      airline: "fly-jinnah",
      airlineName: "Fly Jinnah",
      departureTime: "06:00",
      arrivalTime: "08:35",
      baggage: "20+7 KG",
      meal: false,
      seatsAvailable: 20,
      price: 80000,
      currency: "PKR",
    },
    {
      id: "AG2021",
      date: "01-02-2026",
      sector: "ISB-DXB",
      flight: "PF125",
      airline: "air-sial",
      airlineName: "Air Sial",
      departureTime: "08:30",
      arrivalTime: "11:00",
      baggage: "23+7 KG",
      meal: true,
      seatsAvailable: 25,
      price: 95000,
      currency: "PKR",
    },
    {
      id: "AG2022",
      date: "02-02-2026",
      sector: "ISB-DXB",
      flight: "G9502",
      airline: "air-arabia",
      airlineName: "Air Arabia",
      departureTime: "14:00",
      arrivalTime: "16:30",
      baggage: "20+7 KG",
      meal: false,
      seatsAvailable: 10,
      price: 88000,
      currency: "PKR",
    },
    {
      id: "AG2023",
      date: "03-02-2026",
      sector: "ISB-AUH",
      flight: "PK785",
      airline: "pia",
      airlineName: "PIA",
      departureTime: "10:00",
      arrivalTime: "12:30",
      baggage: "30+7 KG",
      meal: true,
      seatsAvailable: 30,
      price: 92000,
      currency: "PKR",
    },
  ],
  ksa: [
    {
      id: "AG3001",
      date: "28-01-2026",
      sector: "ISB-JED",
      flight: "SV753",
      airline: "saudia",
      airlineName: "Saudia",
      departureTime: "09:00",
      arrivalTime: "12:30",
      baggage: "23+7 KG",
      meal: true,
      seatsAvailable: 18,
      price: 125000,
      currency: "PKR",
    },
  ],
  umrah: [
    {
      id: "AG4001",
      date: "01-02-2026",
      sector: "ISB-JED",
      flight: "SV753",
      airline: "saudia",
      airlineName: "Saudia",
      departureTime: "09:00",
      arrivalTime: "12:30",
      baggage: "23+7 KG",
      meal: true,
      seatsAvailable: 50,
      price: 145000,
      currency: "PKR",
    },
  ],
};
